const fs = require('fs');
const filePath = 'C:/Users/matri/Documents/ClaudeCode/HTML Appz/Schulbildung/Klasse_3-6/Geographie/GeoForscher/index.html';
let content = fs.readFileSync(filePath, 'utf8');

// Find modules array boundaries
const startMarker = 'const modules=[';
const startIdx = content.indexOf(startMarker);

// Find the end: locate STORAGE_KEY and go back
const storageMarker = "const STORAGE_KEY='geoforscher_progress'";
const storageIdx = content.indexOf(storageMarker);
const sectionBetween = content.substring(startIdx, storageIdx);
const lastBracket = sectionBetween.lastIndexOf(']');
const endIdx = startIdx + lastBracket + 1;

const newModules = `const modules=[{id:0,title:'Kontinente im Detail',icon:'\u{1F30D}',duration:'30 Min.',description:'Lerne die 7 Kontinente mit ihren Besonderheiten kennen.',lessons:[{title:'Die 7 Kontinente',content:\`<p>Unsere Erde hat <strong>7 Kontinente</strong> \u2014 riesige Landmassen, die von Ozeanen umgeben sind:</p>
<ol><li>\u{1F30D} <strong>Afrika</strong> \u2014 der zweitgr\u00F6\u00DFte Kontinent mit der Sahara, dem gr\u00F6\u00DFten W\u00FCstengebiet der Erde</li><li>\u{1F30F} <strong>Asien</strong> \u2014 der gr\u00F6\u00DFte und bev\u00F6lkerungsreichste Kontinent mit \u00FCber 4 Milliarden Menschen</li><li>\u{1F30D} <strong>Europa</strong> \u2014 der zweitkleinste Kontinent, bekannt f\u00FCr seine kulturelle Vielfalt</li><li>\u{1F30E} <strong>Nordamerika</strong> \u2014 mit den USA, Kanada und Mexiko</li><li>\u{1F30E} <strong>S\u00FCdamerika</strong> \u2014 Heimat des Amazonas-Regenwaldes</li><li>\u{1F30F} <strong>Australien/Ozeanien</strong> \u2014 der kleinste Kontinent mit einzigartiger Tierwelt</li><li>\u{1F9CA} <strong>Antarktis</strong> \u2014 der k\u00E4lteste Kontinent, fast komplett mit Eis bedeckt</li></ol>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Asien ist der gr\u00F6\u00DFte Kontinent \u2014 er ist gr\u00F6\u00DFer als alle anderen Kontinente zusammen minus Afrika!</div>\`},{title:'Kontinente in Zahlen',content:\`<p>Jeder Kontinent hat besondere <strong>Merkmale</strong>:</p>
<ul><li>\u{1F3D4}\uFE0F <strong>Asien:</strong> 44,6 Mio. km\u00B2 \u2014 h\u00F6chster Berg der Welt (Mount Everest, 8.849 m)</li><li>\u{1F334} <strong>Afrika:</strong> 30,3 Mio. km\u00B2 \u2014 l\u00E4ngster Fluss der Welt (Nil, ca. 6.650 km)</li><li>\u{1F33F} <strong>S\u00FCdamerika:</strong> 17,8 Mio. km\u00B2 \u2014 gr\u00F6\u00DFter Regenwald der Welt (Amazonas)</li><li>\u{1F5FD} <strong>Nordamerika:</strong> 24,7 Mio. km\u00B2 \u2014 drittgr\u00F6\u00DFter Kontinent</li><li>\u{1F9CA} <strong>Antarktis:</strong> 14 Mio. km\u00B2 \u2014 kein Land besitzt sie, nur Forschungsstationen</li><li>\u{1F3F0} <strong>Europa:</strong> 10,2 Mio. km\u00B2 \u2014 rund 50 L\u00E4nder auf kleinem Raum</li><li>\u{1F998} <strong>Australien/Ozeanien:</strong> 8,5 Mio. km\u00B2 \u2014 einzigartige Beuteltiere wie K\u00E4ngurus</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Die Antarktis hat im Winter Temperaturen von bis zu <em>-89,2 \u00B0C</em> \u2014 der k\u00E4lteste gemessene Wert auf der Erde!</div>\`}],quiz:[{q:'Welcher ist der gr\u00F6\u00DFte Kontinent?',a:["Afrika","Asien","Nordamerika","Europa"],_h:75},{q:'Auf welchem Kontinent liegt der Amazonas-Regenwald?',a:["Afrika","Asien","S\u00FCdamerika","Nordamerika"],_h:125},{q:'Welcher Kontinent ist fast komplett mit Eis bedeckt?',a:["Europa","Antarktis","Asien","Australien"],_h:42},{q:'Wie viele Kontinente gibt es?',a:["5","6","7","8"],_h:99},{q:'Auf welchem Kontinent liegt der Mount Everest?',a:["Europa","Afrika","S\u00FCdamerika","Asien"],_h:95}],boss:[{q:'Warum hat Australien so viele einzigartige Tierarten wie K\u00E4ngurus und Koalas?',a:["Weil es dort warm ist","Weil Australien seit Millionen Jahren von anderen Kontinenten isoliert ist","Weil es wenig Menschen gibt","Weil die Tiere importiert wurden"],_h:126},{q:'Warum leben in der Antarktis keine Menschen dauerhaft?',a:["Weil es dort Eisb\u00E4ren gibt","Weil die extremen Temperaturen, fehlende Vegetation und Isolation ein dauerhaftes Leben unm\u00F6glich machen","Weil es verboten ist","Weil es zu klein ist"],_h:126},{q:'Europa ist fl\u00E4chenm\u00E4\u00DFig klein, hat aber rund 50 L\u00E4nder. Warum gibt es dort so viele Staaten?',a:["Weil Europa reich ist","Weil sich durch Geschichte, verschiedene V\u00F6lker, Sprachen und Kulturen viele eigenst\u00E4ndige Staaten entwickelt haben","Weil die UNO das bestimmt hat","Weil die L\u00E4nder sehr klein sind"],_h:126}]},{id:1,title:'Klimazonen',icon:'\u{1F321}\uFE0F',duration:'30 Min.',description:'Entdecke die verschiedenen Klimazonen der Erde und ihre Merkmale.',lessons:[{title:'Was sind Klimazonen?',content:\`<p><strong>Klimazonen</strong> sind gro\u00DFe Gebiete der Erde mit \u00E4hnlichem Klima. Die Sonne erw\u00E4rmt die Erde unterschiedlich stark \u2014 je nach Breitengrad:</p>
<ul><li>\u2600\uFE0F <strong>Tropische Zone</strong> (um den \u00C4quator) \u2014 ganzj\u00E4hrig warm und feucht, Durchschnittstemperatur \u00FCber 18 \u00B0C</li><li>\u{1F324}\uFE0F <strong>Subtropische Zone</strong> \u2014 hei\u00DFe, trockene Sommer und milde Winter</li><li>\u{1F326}\uFE0F <strong>Gem\u00E4\u00DFigte Zone</strong> \u2014 vier Jahreszeiten (Fr\u00FChling, Sommer, Herbst, Winter), hier liegt Deutschland!</li><li>\u2744\uFE0F <strong>Subpolare Zone</strong> \u2014 lange, kalte Winter und kurze, k\u00FChle Sommer</li><li>\u{1F9CA} <strong>Polare Zone</strong> (an den Polen) \u2014 extrem kalt, fast kein Pflanzenwuchs</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Je n\u00E4her am \u00C4quator, desto w\u00E4rmer \u2014 je n\u00E4her an den Polen, desto k\u00E4lter!</div>\`},{title:'Klimafaktoren',content:\`<p>Das Klima eines Ortes wird von verschiedenen <strong>Faktoren</strong> beeinflusst:</p>
<ul><li>\u{1F310} <strong>Breitengrad</strong> \u2014 N\u00E4he zum \u00C4quator bestimmt die Sonneneinstrahlung</li><li>\u{1F3D4}\uFE0F <strong>H\u00F6henlage</strong> \u2014 pro 1.000 m H\u00F6he sinkt die Temperatur um ca. 6 \u00B0C</li><li>\u{1F30A} <strong>Meeresn\u00E4he</strong> \u2014 K\u00FCstengebiete haben mildere Temperaturen als das Inland</li><li>\u{1F32C}\uFE0F <strong>Winde und Meeresstr\u00F6mungen</strong> \u2014 der Golfstrom w\u00E4rmt Europa!</li><li>\u{1F332} <strong>Vegetation</strong> \u2014 W\u00E4lder beeinflussen Luftfeuchtigkeit und Temperatur</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Ohne den Golfstrom w\u00E4re es in Deutschland so kalt wie in Kanada auf dem gleichen Breitengrad!</div>\`}],quiz:[{q:'In welcher Klimazone liegt Deutschland?',a:["Tropische Zone","Subtropische Zone","Gem\u00E4\u00DFigte Zone","Polare Zone"],_h:41},{q:'Was passiert mit der Temperatur, wenn man einen Berg hochsteigt?',a:["Sie steigt","Sie sinkt","Sie bleibt gleich","Sie schwankt zuf\u00E4llig"],_h:126},{q:'Was ist der \u00C4quator?',a:["Ein Fluss","Eine gedachte Linie um die Mitte der Erde","Ein Kontinent","Ein Gebirge"],_h:42},{q:'Welche Klimazone ist ganzj\u00E4hrig warm und feucht?',a:["Gem\u00E4\u00DFigte Zone","Polare Zone","Tropische Zone","Subpolare Zone"],_h:99},{q:'Was erw\u00E4rmt das Klima in Europa besonders?',a:["Die Sahara","Der Mond","Der Golfstrom","Die Alpen"],_h:93}],boss:[{q:'Warum gibt es auf der Erde \u00FCberhaupt verschiedene Klimazonen?',a:["Weil die L\u00E4nder verschieden sind","Weil die kugelf\u00F6rmige Erde an verschiedenen Stellen unterschiedlich stark von der Sonne bestrahlt wird","Weil es Zufall ist","Weil der Mond das beeinflusst"],_h:126},{q:'Warum ist es in den Bergen k\u00E4lter, obwohl man n\u00E4her an der Sonne ist?',a:["Weil die Sonne dort schw\u00E4cher scheint","Weil die Luft in der H\u00F6he d\u00FCnner ist und weniger W\u00E4rme speichern kann","Weil es dort mehr Wind gibt","Weil Schnee alles k\u00FChlt"],_h:126},{q:'Eine Stadt am Meer hat mildere Winter als eine Stadt im Landesinneren auf dem gleichen Breitengrad. Warum?',a:["Weil das Meer Fische hat","Weil Wasser W\u00E4rme langsamer aufnimmt und abgibt als Land und so als Temperaturspeicher wirkt","Weil am Meer mehr Sonne scheint","Weil das Wasser die Stadt sch\u00FCtzt"],_h:126}]},{id:2,title:'Naturkatastrophen',icon:'\u{1F30B}',duration:'30 Min.',description:'Erfahre wie Erdbeben, Vulkane und andere Naturgewalten entstehen.',lessons:[{title:'Erdbeben und Vulkane',content:\`<p>Die <strong>Erdkruste</strong> besteht aus riesigen Platten, die sich langsam bewegen \u2014 die <strong>tektonischen Platten</strong>:</p>
<ul><li>\u{1F30D} Es gibt etwa <strong>15 gro\u00DFe Platten</strong>, die auf dem hei\u00DFen Erdmantel schwimmen</li><li>\u{1F4A5} <strong>Erdbeben</strong> entstehen, wenn Platten aneinander reiben, kollidieren oder auseinanderdriften</li><li>\u{1F30B} <strong>Vulkane</strong> bilden sich oft an Plattengrenzen, wo hei\u00DFes Magma aus dem Erdinneren aufsteigt</li><li>\u{1F525} Der <strong>Pazifische Feuerring</strong> ist ein G\u00FCrtel um den Pazifik mit besonders vielen Vulkanen und Erdbeben</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Die st\u00E4rksten Erdbeben werden mit der <strong>Richterskala</strong> gemessen \u2014 ab St\u00E4rke 6 k\u00F6nnen sie gro\u00DFe Sch\u00E4den verursachen!</div>\`},{title:'St\u00FCrme und \u00DCberschwemmungen',content:\`<p>Neben Erdbeben und Vulkanen gibt es weitere <strong>Naturkatastrophen</strong>:</p>
<ul><li>\u{1F30A} <strong>Tsunamis</strong> \u2014 riesige Wellen, ausgel\u00F6st durch Seebeben oder Unterwasser-Vulkanausbr\u00FCche</li><li>\u{1F32A}\uFE0F <strong>Tornados</strong> \u2014 schnell rotierende Lufts\u00E4ulen, besonders in den USA ("Tornado Alley")</li><li>\u{1F300} <strong>Hurrikane/Taifune</strong> \u2014 gewaltige tropische Wirbelst\u00FCrme \u00FCber warmem Ozeanwasser</li><li>\u{1F327}\uFE0F <strong>\u00DCberschwemmungen</strong> \u2014 durch Starkregen, Schneeschmelze oder Sturmfluten</li><li>\u{1F3DC}\uFE0F <strong>D\u00FCrren</strong> \u2014 lange Trockenperioden ohne Regen</li></ul>
<div class="info-box">\u26A0\uFE0F <strong>Wichtig:</strong> Fr\u00FChwarnsysteme k\u00F6nnen Leben retten \u2014 bei Tsunami-Alarm sofort auf h\u00F6her gelegenes Gel\u00E4nde fl\u00FCchten!</div>\`}],quiz:[{q:'Was sind tektonische Platten?',a:["Teller in der K\u00FCche","Gro\u00DFe Teile der Erdkruste, die sich langsam bewegen","Wolkenformationen","Meeresstr\u00F6mungen"],_h:75},{q:'Wo gibt es besonders viele Vulkane und Erdbeben?',a:["In Europa","Am Pazifischen Feuerring","In Afrika","Am Nordpol"],_h:126},{q:'Was l\u00F6st einen Tsunami aus?',a:["Starker Wind","Ein Seebeben oder Unterwasser-Vulkanausbruch","Regen","Ebbe und Flut"],_h:42},{q:'Mit welcher Skala misst man die St\u00E4rke von Erdbeben?',a:["Celsius-Skala","Beaufort-Skala","Richterskala","Dezibel-Skala"],_h:99},{q:'Was ist ein Hurrikan?',a:["Ein Erdbeben","Ein Vulkanausbruch","Ein tropischer Wirbelsturm","Eine \u00DCberschwemmung"],_h:93}],boss:[{q:'Warum gibt es am Pazifischen Feuerring so viele Vulkane?',a:["Weil es dort hei\u00DF ist","Weil dort besonders viele tektonische Platten aufeinandertreffen und Magma aufsteigen kann","Weil der Pazifik gro\u00DF ist","Weil das Wasser die Vulkane aktiviert"],_h:126},{q:'Warum k\u00F6nnen Wissenschaftler Erdbeben nicht genau vorhersagen?',a:["Weil sie keine Instrumente haben","Weil die Spannungen in der Erdkruste sich unregelm\u00E4\u00DFig aufbauen und l\u00F6sen","Weil sie nicht genug forschen","Weil Erdbeben zuf\u00E4llig sind"],_h:126},{q:'Warum werden Hurrikane st\u00E4rker, wenn sie \u00FCber warmem Wasser ziehen?',a:["Weil warmes Wasser leichter ist","Weil warmes Wasser mehr verdunstet und dem Sturm Energie in Form von Wasserdampf liefert","Weil warmes Wasser den Wind beschleunigt","Weil es dort keine Inseln gibt"],_h:126}]},{id:3,title:'Fl\u00FCsse und Seen',icon:'\u{1F3DE}\uFE0F',duration:'30 Min.',description:'Entdecke die wichtigsten Gew\u00E4sser der Erde und ihre Bedeutung.',lessons:[{title:'Die gr\u00F6\u00DFten Fl\u00FCsse der Welt',content:\`<p><strong>Fl\u00FCsse</strong> sind lebenswichtig \u2014 sie liefern Trinkwasser, Nahrung und Transportwege:</p>
<ul><li>\u{1F3C6} <strong>Nil</strong> (Afrika) \u2014 ca. 6.650 km, der l\u00E4ngste Fluss der Welt</li><li>\u{1F30A} <strong>Amazonas</strong> (S\u00FCdamerika) \u2014 ca. 6.400 km, f\u00FChrt das meiste Wasser aller Fl\u00FCsse</li><li>\u{1F409} <strong>Jangtse</strong> (Asien) \u2014 ca. 6.300 km, der l\u00E4ngste Fluss Asiens</li><li>\u{1F1EA}\u{1F1FA} <strong>Donau</strong> (Europa) \u2014 ca. 2.850 km, flie\u00DFt durch 10 L\u00E4nder</li><li>\u{1F1E9}\u{1F1EA} <strong>Rhein</strong> (Europa) \u2014 ca. 1.230 km, wichtigste Wasserstra\u00DFe Deutschlands</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Ein <strong>Flusssystem</strong> besteht aus dem Hauptfluss und allen Nebenfl\u00FCssen, die in ihn m\u00FCnden \u2014 wie ein verzweigter Baum!</div>\`},{title:'Seen und ihre Bedeutung',content:\`<p><strong>Seen</strong> sind stehende Gew\u00E4sser mit gro\u00DFer Bedeutung f\u00FCr Mensch und Natur:</p>
<ul><li>\u{1F3D4}\uFE0F <strong>Baikalsee</strong> (Russland) \u2014 der tiefste See der Welt (1.642 m) mit 20% des weltweiten S\u00FC\u00DFwassers</li><li>\u{1F30A} <strong>Kaspisches Meer</strong> \u2014 der gr\u00F6\u00DFte See der Welt (trotz des Namens ein See!)</li><li>\u{1F41F} <strong>Victoriasee</strong> (Afrika) \u2014 der gr\u00F6\u00DFte See Afrikas, wichtig f\u00FCr Fischfang</li><li>\u{1F1E9}\u{1F1EA} <strong>Bodensee</strong> \u2014 der gr\u00F6\u00DFte See Deutschlands, geteilt mit \u00D6sterreich und der Schweiz</li></ul>
<p><strong>Warum Gew\u00E4sser sch\u00FCtzen?</strong></p>
<ul><li>\u{1F6B0} Trinkwasserversorgung f\u00FCr Milliarden Menschen</li><li>\u{1F438} Lebensraum f\u00FCr Tiere und Pflanzen</li><li>\u{1F6A2} Transportwege f\u00FCr Handel</li><li>\u26A1 Energiegewinnung durch Wasserkraft</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Nur etwa <em>3 %</em> des Wassers auf der Erde ist S\u00FC\u00DFwasser \u2014 und davon ist das meiste als Eis an den Polen gebunden!</div>\`}],quiz:[{q:'Welcher ist der l\u00E4ngste Fluss der Welt?',a:["Amazonas","Nil","Jangtse","Donau"],_h:75},{q:'Welcher See ist der tiefste der Welt?',a:["Bodensee","Victoriasee","Baikalsee","Kaspisches Meer"],_h:125},{q:'Durch wie viele L\u00E4nder flie\u00DFt die Donau?',a:["5","8","10","12"],_h:41},{q:'Wie viel Prozent des Wassers auf der Erde ist S\u00FC\u00DFwasser?',a:["3 %","10 %","30 %","50 %"],_h:97},{q:'Welcher Fluss f\u00FChrt am meisten Wasser?',a:["Nil","Rhein","Donau","Amazonas"],_h:95}],boss:[{q:'Warum wird der Nil als Lebensader \u00C4gyptens bezeichnet?',a:["Weil er sch\u00F6n aussieht","Weil er in der W\u00FCste Wasser f\u00FCr Landwirtschaft, Trinkwasser und Transport liefert","Weil er der l\u00E4ngste ist","Weil er blau ist"],_h:126},{q:'Warum enth\u00E4lt der Baikalsee allein 20 % des weltweiten S\u00FC\u00DFwassers?',a:["Weil er breit ist","Weil er mit 1.642 m extrem tief ist und ein gro\u00DFes Volumen hat","Weil es viel regnet","Weil er in Russland liegt"],_h:126},{q:'Warum ist Wasserverschmutzung f\u00FCr Fl\u00FCsse besonders gef\u00E4hrlich?',a:["Weil Fl\u00FCsse schnell flie\u00DFen","Weil verschmutztes Wasser flussabw\u00E4rts transportiert wird und ganze \u00D6kosysteme und Trinkwasserquellen vergiften kann","Weil Fische nicht schwimmen k\u00F6nnen","Weil das Wasser dann stinkt"],_h:126}]},{id:4,title:'Gebirge der Welt',icon:'\u{1F3D4}\uFE0F',duration:'30 Min.',description:'Erforsche die h\u00F6chsten Gebirge und wie sie entstanden sind.',lessons:[{title:'Die gro\u00DFen Gebirge',content:\`<p><strong>Gebirge</strong> bedecken etwa ein Viertel der Erdoberfl\u00E4che und sind Lebensraum f\u00FCr viele Menschen und Tiere:</p>
<ul><li>\u{1F3D4}\uFE0F <strong>Himalaya</strong> (Asien) \u2014 das h\u00F6chste Gebirge mit dem Mount Everest (8.849 m)</li><li>\u26F0\uFE0F <strong>Alpen</strong> (Europa) \u2014 das wichtigste Gebirge Europas, erstreckt sich \u00FCber 8 L\u00E4nder</li><li>\u{1F30E} <strong>Anden</strong> (S\u00FCdamerika) \u2014 das l\u00E4ngste Gebirge der Welt (ca. 7.500 km)</li><li>\u{1F5FB} <strong>Rocky Mountains</strong> (Nordamerika) \u2014 \u00FCber 4.800 km lang</li><li>\u{1F30D} <strong>Atlas-Gebirge</strong> (Afrika) \u2014 trennt die Sahara vom Mittelmeerraum</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Die Alpen sind das Wasserschloss Europas \u2014 viele gro\u00DFe Fl\u00FCsse wie Rhein, Rhone und Po entspringen hier!</div>\`},{title:'Wie Gebirge entstehen',content:\`<p>Gebirge entstehen durch verschiedene <strong>geologische Prozesse</strong>:</p>
<ul><li>\u{1F504} <strong>Faltengebirge</strong> \u2014 wenn zwei tektonische Platten aufeinander zudr\u00FCcken, faltet sich die Erdkruste nach oben (z.B. Himalaya, Alpen)</li><li>\u2B06\uFE0F <strong>Vulkanische Gebirge</strong> \u2014 durch Vulkanausbr\u00FCche entstehen Berge aus erstarrter Lava</li><li>\u2B07\uFE0F <strong>Bruchschollengebirge</strong> \u2014 Erdkrustenteile werden angehoben (z.B. Harz)</li></ul>
<p><strong>H\u00F6henstufen der Vegetation:</strong></p>
<ol><li>\u{1F333} Laubwald (bis ca. 800 m)</li><li>\u{1F332} Nadelwald (bis ca. 1.800 m)</li><li>\u{1F33F} Almwiesen (bis ca. 2.500 m)</li><li>\u{1FAA8} Fels und Ger\u00F6ll (bis ca. 3.500 m)</li><li>\u2744\uFE0F Eis und Schnee (dar\u00FCber)</li></ol>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Der Himalaya w\u00E4chst noch heute \u2014 ca. <em>1 cm pro Jahr</em>, weil die Indische Platte weiter gegen die Eurasische Platte dr\u00FCckt!</div>\`}],quiz:[{q:'Welches ist das h\u00F6chste Gebirge der Welt?',a:["Alpen","Anden","Himalaya","Rocky Mountains"],_h:41},{q:'Wie hoch ist der Mount Everest?',a:["6.849 m","7.849 m","8.849 m","9.849 m"],_h:125},{q:'Welches ist das l\u00E4ngste Gebirge der Welt?',a:["Himalaya","Alpen","Rocky Mountains","Anden"],_h:40},{q:'Wie entstehen Faltengebirge?',a:["Durch Wind","Durch Regen","Wenn tektonische Platten aufeinander zudr\u00FCcken","Durch Vulkanausbr\u00FCche"],_h:99},{q:'In welchem Gebirge liegt der Mont Blanc?',a:["Himalaya","Alpen","Anden","Rocky Mountains"],_h:93}],boss:[{q:'Warum werden Gebirge im Laufe der Zeit kleiner?',a:["Weil sie zusammenfallen","Weil Verwitterung, Erosion durch Wind, Wasser und Eis sie langsam abtragen","Weil die Erde schrumpft","Weil Tiere sie zerst\u00F6ren"],_h:126},{q:'Warum finden wir manchmal Fossilien von Meerestieren auf hohen Bergen?',a:["Weil V\u00F6gel sie dorthin tragen","Weil diese Gesteinsschichten einst am Meeresboden lagen und durch Plattentektonik hochgedr\u00FCckt wurden","Weil es dort mal ein Aquarium gab","Weil die Fossilien gef\u00E4lscht sind"],_h:126},{q:'Warum wird die Luft auf Bergen d\u00FCnner, und was bedeutet das f\u00FCr den Menschen?',a:["Weil es dort k\u00E4lter ist","Weil mit zunehmender H\u00F6he der Luftdruck sinkt und weniger Sauerstoff verf\u00FCgbar ist, was zu H\u00F6henkrankheit f\u00FChren kann","Weil der Wind die Luft wegbl\u00E4st","Weil B\u00E4ume fehlen"],_h:126}]},{id:5,title:'Bev\u00F6lkerung',icon:'\u{1F465}',duration:'30 Min.',description:'Erfahre wie die Weltbev\u00F6lkerung verteilt ist und wie sie w\u00E4chst.',lessons:[{title:'Die Weltbev\u00F6lkerung',content:\`<p>Auf der Erde leben \u00FCber <strong>8 Milliarden Menschen</strong> (Stand 2024). Aber die Verteilung ist sehr ungleich:</p>
<ul><li>\u{1F30F} <strong>Asien</strong> \u2014 ca. 4,7 Milliarden (etwa 60 % der Weltbev\u00F6lkerung!)</li><li>\u{1F30D} <strong>Afrika</strong> \u2014 ca. 1,4 Milliarden (w\u00E4chst am schnellsten)</li><li>\u{1F30D} <strong>Europa</strong> \u2014 ca. 750 Millionen (Bev\u00F6lkerung stagniert)</li><li>\u{1F30E} <strong>Nordamerika</strong> \u2014 ca. 580 Millionen</li><li>\u{1F30E} <strong>S\u00FCdamerika</strong> \u2014 ca. 430 Millionen</li><li>\u{1F30F} <strong>Australien/Ozeanien</strong> \u2014 ca. 45 Millionen</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> <strong>Indien</strong> hat 2023 China als bev\u00F6lkerungsreichstes Land \u00FCberholt \u2014 mit \u00FCber <em>1,4 Milliarden</em> Menschen!</div>\`},{title:'Megast\u00E4dte und Landflucht',content:\`<p><strong>Megast\u00E4dte</strong> sind St\u00E4dte mit mehr als 10 Millionen Einwohnern:</p>
<ul><li>\u{1F3D9}\uFE0F <strong>Tokio</strong> (Japan) \u2014 ca. 37 Millionen \u2014 gr\u00F6\u00DFter Ballungsraum der Welt</li><li>\u{1F3D9}\uFE0F <strong>Delhi</strong> (Indien) \u2014 ca. 32 Millionen</li><li>\u{1F3D9}\uFE0F <strong>Shanghai</strong> (China) \u2014 ca. 29 Millionen</li><li>\u{1F3D9}\uFE0F <strong>S\u00E3o Paulo</strong> (Brasilien) \u2014 ca. 22 Millionen</li></ul>
<p><strong>Landflucht</strong> bedeutet, dass immer mehr Menschen vom Land in die Stadt ziehen:</p>
<ul><li>Heute lebt \u00FCber die H\u00E4lfte der Menschheit in <strong>St\u00E4dten</strong></li><li>In St\u00E4dten gibt es mehr <strong>Arbeitspl\u00E4tze</strong>, Schulen und Krankenh\u00E4user</li><li>Aber: Probleme wie <strong>Wohnungsnot</strong>, Verkehr und Umweltverschmutzung nehmen zu</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Bis 2050 werden voraussichtlich <em>zwei Drittel</em> aller Menschen in St\u00E4dten leben!</div>\`}],quiz:[{q:'Wie viele Menschen leben ungef\u00E4hr auf der Erde?',a:["4 Milliarden","6 Milliarden","8 Milliarden","12 Milliarden"],_h:41},{q:'Auf welchem Kontinent leben die meisten Menschen?',a:["Europa","Asien","Afrika","Nordamerika"],_h:126},{q:'Was ist eine Megastadt?',a:["Eine Stadt mit Wolkenkratzern","Eine Stadt mit \u00FCber 10 Millionen Einwohnern","Eine Hauptstadt","Eine Stadt am Meer"],_h:42},{q:'Welches Land hat die meisten Einwohner?',a:["China","Indien","USA","Brasilien"],_h:96},{q:'Was bedeutet Landflucht?',a:["Flucht vor Naturkatastrophen","Menschen ziehen vom Land in die Stadt","Tiere verlassen den Wald","Bauern geben auf"],_h:93}],boss:[{q:'Warum w\u00E4chst die Bev\u00F6lkerung in Afrika besonders schnell?',a:["Weil Afrika gro\u00DF ist","Weil dort hohe Geburtenraten herrschen, die Kindersterblichkeit sinkt und die medizinische Versorgung sich verbessert","Weil viele Menschen nach Afrika ziehen","Weil es dort warm ist"],_h:126},{q:'Welche Probleme entstehen, wenn Megast\u00E4dte zu schnell wachsen?',a:["Es gibt mehr Feiertage","Wohnungsnot, Verkehrschaos, Umweltverschmutzung und unzureichende Infrastruktur","Die H\u00E4user werden sch\u00F6ner","Es wird ruhiger"],_h:126},{q:'Warum leben fast keine Menschen in der Sahara, obwohl sie riesig ist?',a:["Weil es verboten ist","Weil extreme Hitze, Wassermangel und fehlende Vegetation das Leben dort fast unm\u00F6glich machen","Weil sie zu hoch liegt","Weil es dort Krieg gibt"],_h:126}]},{id:6,title:'Rohstoffe',icon:'\u{1F48E}',duration:'30 Min.',description:'Lerne welche Bodensch\u00E4tze die Erde bietet und warum sie wertvoll sind.',lessons:[{title:'Bodensch\u00E4tze der Erde',content:\`<p><strong>Rohstoffe</strong> sind Materialien, die wir aus der Natur gewinnen. Sie sind die Grundlage unserer Wirtschaft:</p>
<ul><li>\u26FD <strong>Erd\u00F6l</strong> \u2014 "schwarzes Gold", wichtig f\u00FCr Treibstoff, Plastik und Chemie. Gr\u00F6\u00DFte Vorkommen: Saudi-Arabien, USA, Russland</li><li>\u{1F48E} <strong>Diamanten</strong> \u2014 h\u00E4rtestes nat\u00FCrliches Material, wichtig f\u00FCr Schmuck und Industrie</li><li>\u{1FAA8} <strong>Eisenerz</strong> \u2014 Grundstoff f\u00FCr Stahl (Br\u00FCcken, Autos, Geb\u00E4ude)</li><li>\u{1F50B} <strong>Lithium</strong> \u2014 unverzichtbar f\u00FCr Batterien in Handys und Elektroautos</li><li>\u{1F947} <strong>Gold</strong> \u2014 wertvolles Edelmetall, W\u00E4hrungsreserve und Schmuck</li><li>\u26AB <strong>Kohle</strong> \u2014 \u00E4ltester fossiler Brennstoff, wird zur Stromerzeugung verbrannt</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Fossile Rohstoffe wie Erd\u00F6l, Kohle und Erdgas sind in Millionen von Jahren entstanden \u2014 wenn sie verbraucht sind, kommen sie nicht wieder!</div>\`},{title:'Erneuerbare und nicht-erneuerbare Rohstoffe',content:\`<p>Man unterscheidet zwei Arten von Rohstoffen:</p>
<ul><li>\u274C <strong>Nicht-erneuerbare Rohstoffe:</strong> Erd\u00F6l, Kohle, Erdgas, Erze \u2014 sie brauchen Millionen Jahre zur Entstehung</li><li>\u2705 <strong>Erneuerbare Rohstoffe:</strong> Holz, Wolle, Baumwolle, Naturkautschuk \u2014 sie wachsen nach</li></ul>
<p><strong>Recycling</strong> ist besonders wichtig f\u00FCr nicht-erneuerbare Rohstoffe:</p>
<ul><li>\u267B\uFE0F Aus Altpapier wird neues Papier</li><li>\u267B\uFE0F Aus Altglas werden neue Flaschen</li><li>\u267B\uFE0F Alte Handys enthalten wertvolle Metalle wie Gold, Silber und Kupfer</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> In einer Tonne alter Handys steckt mehr <em>Gold</em> als in einer Tonne Golderz aus einer Mine!</div>\`}],quiz:[{q:'Was ist Erd\u00F6l?',a:["Eine Pflanze","Ein fossiler Rohstoff aus urzeitlichen Organismen","Ein Mineral","Fl\u00FCssiges Gold"],_h:75},{q:'Welcher Rohstoff wird f\u00FCr Handy-Batterien ben\u00F6tigt?',a:["Gold","Lithium","Eisen","Diamant"],_h:126},{q:'Was sind erneuerbare Rohstoffe?',a:["Erd\u00F6l und Kohle","Rohstoffe, die nachwachsen k\u00F6nnen wie Holz","Seltene Erden","Edelsteine"],_h:42},{q:'Warum ist Recycling wichtig?',a:["Weil es Spa\u00DF macht","Weil es wertvolle Rohstoffe spart und die Umwelt schont","Weil es Pflicht ist","Weil M\u00FCll sch\u00F6n ist"],_h:96},{q:'Wo gibt es die gr\u00F6\u00DFten Erd\u00F6lvorkommen?',a:["Deutschland","Australien","Saudi-Arabien, USA, Russland","Japan"],_h:93}],boss:[{q:'Warum wird Erd\u00F6l als schwarzes Gold bezeichnet?',a:["Weil es schwarz und teuer ist","Weil es extrem wertvoll ist, da die gesamte moderne Wirtschaft von Erd\u00F6l abh\u00E4ngt \u2014 von Treibstoff bis Plastik","Weil es gl\u00E4nzt","Weil es selten ist"],_h:126},{q:'Warum verursacht der Abbau von Rohstoffen oft Umweltprobleme?',a:["Weil Maschinen laut sind","Weil W\u00E4lder gerodet, B\u00F6den vergiftet und Gew\u00E4sser verschmutzt werden, um an die Rohstoffe zu gelangen","Weil es stinkt","Weil die Arbeiter krank werden"],_h:126},{q:'Warum sind seltene Erden trotz ihres Namens so wichtig f\u00FCr Handys und Elektroautos?',a:["Weil sie sch\u00F6n aussehen","Weil sie besondere magnetische und elektrische Eigenschaften haben, die f\u00FCr Hightech-Produkte unverzichtbar sind","Weil sie billig sind","Weil China sie verkauft"],_h:126}]},{id:7,title:'Landwirtschaft',icon:'\u{1F33E}',duration:'30 Min.',description:'Erfahre wie Nahrung angebaut wird und was fairer Handel bedeutet.',lessons:[{title:'Ackerbau und Viehzucht',content:\`<p>Die <strong>Landwirtschaft</strong> ern\u00E4hrt die gesamte Menschheit. Es gibt verschiedene Formen:</p>
<ul><li>\u{1F33E} <strong>Ackerbau</strong> \u2014 Anbau von Getreide (Weizen, Reis, Mais), Gem\u00FCse und Obst</li><li>\u{1F404} <strong>Viehzucht</strong> \u2014 Haltung von Rindern, Schweinen, H\u00FChnern f\u00FCr Fleisch, Milch, Eier</li><li>\u{1F30D} <strong>Plantagen</strong> \u2014 gro\u00DFe Anbaufl\u00E4chen f\u00FCr Exportprodukte (Kaffee, Kakao, Bananen)</li><li>\u{1F331} <strong>Subsistenzwirtschaft</strong> \u2014 Bauern produzieren nur f\u00FCr den eigenen Bedarf</li></ul>
<p><strong>Wichtige Nutzpflanzen der Welt:</strong></p>
<ul><li>\u{1F35A} <strong>Reis</strong> \u2014 Hauptnahrungsmittel f\u00FCr \u00FCber 3 Milliarden Menschen in Asien</li><li>\u{1F33D} <strong>Mais</strong> \u2014 vielseitig: Nahrung, Tierfutter, Bioethanol</li><li>\u{1F33E} <strong>Weizen</strong> \u2014 Grundlage f\u00FCr Brot in Europa und Nordamerika</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Nur etwa <strong>10 %</strong> der Erdoberfl\u00E4che sind f\u00FCr Ackerbau geeignet!</div>\`},{title:'Fairer Handel und Bew\u00E4sserung',content:\`<p><strong>Monokulturen</strong> sind Felder, auf denen immer nur <em>eine Pflanze</em> angebaut wird:</p>
<ul><li>\u2795 Vorteil: Effizient und leicht zu ernten</li><li>\u2796 Nachteil: B\u00F6den werden ausgelaugt, Sch\u00E4dlinge breiten sich leichter aus</li></ul>
<p><strong>Bew\u00E4sserung</strong> ist in trockenen Gebieten lebenswichtig:</p>
<ul><li>\u{1F4A7} Tr\u00F6pfchenbew\u00E4sserung spart bis zu <strong>70 % Wasser</strong> gegen\u00FCber \u00DCberflutung</li><li>\u{1F3DC}\uFE0F In Israel wird damit sogar in der W\u00FCste Landwirtschaft betrieben</li></ul>
<p><strong>Fairer Handel (Fair Trade)</strong> bedeutet:</p>
<ul><li>\u2705 Gerechte Bezahlung f\u00FCr Bauern in Entwicklungsl\u00E4ndern</li><li>\u2705 Verbot von Kinderarbeit</li><li>\u2705 Umweltschonender Anbau</li><li>\u{1F3F7}\uFE0F Erkennbar am <strong>Fairtrade-Siegel</strong></li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> F\u00FCr eine Tasse Kaffee bekommt ein Kaffeebauer in Afrika oft nur <em>wenige Cent</em> \u2014 Fair Trade \u00E4ndert das!</div>\`}],quiz:[{q:'Was ist Subsistenzwirtschaft?',a:["Gro\u00DFe Plantagen","Bauern produzieren nur f\u00FCr den eigenen Bedarf","Industrielle Landwirtschaft","Handel mit anderen L\u00E4ndern"],_h:75},{q:'Welches Getreide ist Hauptnahrungsmittel f\u00FCr \u00FCber 3 Milliarden Menschen?',a:["Weizen","Mais","Reis","Hafer"],_h:125},{q:'Was bedeutet Fair Trade?',a:["Freier Handel ohne Regeln","Gerechte Bezahlung und gute Arbeitsbedingungen f\u00FCr Produzenten","Handel nur in Europa","Billige Produkte kaufen"],_h:42},{q:'Was ist ein Nachteil von Monokulturen?',a:["Sie sind zu bunt","B\u00F6den werden ausgelaugt und Sch\u00E4dlinge breiten sich aus","Sie brauchen zu wenig Wasser","Sie wachsen zu schnell"],_h:96},{q:'Wie viel Prozent der Erdoberfl\u00E4che sind f\u00FCr Ackerbau geeignet?',a:["2 %","10 %","30 %","50 %"],_h:93}],boss:[{q:'Warum ist Reis das wichtigste Nahrungsmittel in Asien, aber nicht in Europa?',a:["Weil Asiaten Reis m\u00F6gen","Weil Reis viel W\u00E4rme und Wasser braucht, die in den tropischen Klimazonen Asiens reichlich vorhanden sind","Weil es in Europa keinen Reis gibt","Weil Reis billig ist"],_h:126},{q:'Warum k\u00F6nnen Monokulturen langfristig zu Ernteausf\u00E4llen f\u00FChren?',a:["Weil die Pflanzen zu gro\u00DF werden","Weil der Boden einseitig ausgelaugt wird und sich Sch\u00E4dlinge auf eine Pflanzenart spezialisieren k\u00F6nnen","Weil es zu viel regnet","Weil die Maschinen kaputt gehen"],_h:126},{q:'Warum brauchen wir Fairtrade-Siegel, wenn es doch einen freien Weltmarkt gibt?',a:["Weil Siegel sch\u00F6n aussehen","Weil der freie Markt oft zu unfairen Preisen f\u00FChrt, die Bauern in Armut halten, und Fairtrade gerechte Mindestpreise garantiert","Weil es Gesetz ist","Weil Kunden das verlangen"],_h:126}]},{id:8,title:'Globalisierung',icon:'\u{1F310}',duration:'30 Min.',description:'Verstehe wie die Welt durch Handel, Transport und Internet vernetzt ist.',lessons:[{title:'Was ist Globalisierung?',content:\`<p><strong>Globalisierung</strong> bedeutet, dass die Welt immer st\u00E4rker vernetzt wird \u2014 wirtschaftlich, kulturell und politisch:</p>
<ul><li>\u{1F6A2} <strong>Welthandel</strong> \u2014 Waren werden \u00FCber Ozeane transportiert (90 % per Containerschiff!)</li><li>\u2708\uFE0F <strong>Reisen</strong> \u2014 heute kann man in wenigen Stunden um die halbe Welt fliegen</li><li>\u{1F4F1} <strong>Internet</strong> \u2014 Kommunikation in Echtzeit mit der ganzen Welt</li><li>\u{1F3AC} <strong>Kultur</strong> \u2014 Filme, Musik und Mode verbreiten sich weltweit</li><li>\u{1F3ED} <strong>Produktion</strong> \u2014 ein Handy enth\u00E4lt Teile aus \u00FCber 30 verschiedenen L\u00E4ndern!</li></ul>
<div class="info-box">\u{1F4A1} <strong>Merke:</strong> Globalisierung hat <em>Vorteile</em> (Wohlstand, Austausch) und <em>Nachteile</em> (Umweltbelastung, Ausbeutung)!</div>\`},{title:'Transportwege und Auswirkungen',content:\`<p>Verschiedene <strong>Transportwege</strong> verbinden die Welt:</p>
<ul><li>\u{1F6A2} <strong>Containerschiffe</strong> \u2014 transportieren 90 % aller Handelsg\u00FCter \u00FCber die Meere</li><li>\u2708\uFE0F <strong>Flugzeuge</strong> \u2014 schnell, aber teuer und klimasch\u00E4dlich</li><li>\u{1F682} <strong>Eisenbahnen</strong> \u2014 die "Neue Seidenstra\u00DFe" verbindet China mit Europa per Zug</li><li>\u{1F6E3}\uFE0F <strong>LKW</strong> \u2014 f\u00FCr den Transport innerhalb von L\u00E4ndern</li></ul>
<p><strong>Auswirkungen der Globalisierung:</strong></p>
<ul><li>\u2705 Mehr Auswahl an Produkten aus aller Welt</li><li>\u2705 Kultureller Austausch und Verst\u00E4ndigung</li><li>\u274C Umweltbelastung durch lange Transportwege</li><li>\u274C Arbeitsbedingungen in manchen Produktionsl\u00E4ndern sind schlecht</li><li>\u274C Lokale Produkte werden durch billige Importe verdr\u00E4ngt</li></ul>
<div class="info-box">\u{1F50D} <strong>Wusstest du?</strong> Eine Jeans reist durchschnittlich <em>50.000 km</em> um die Welt, bevor sie im Laden liegt \u2014 von der Baumwollernte bis zum Verkauf!</div>\`}],quiz:[{q:'Was bedeutet Globalisierung?',a:["Dass alle L\u00E4nder gleich sind","Dass die Welt wirtschaftlich, kulturell und politisch immer st\u00E4rker vernetzt ist","Dass jeder reisen muss","Dass es nur noch ein Land gibt"],_h:75},{q:'Wie werden die meisten Handelswaren weltweit transportiert?',a:["Per Flugzeug","Per LKW","Per Containerschiff","Per Eisenbahn"],_h:125},{q:'Aus wie vielen L\u00E4ndern stammen die Teile eines Handys ungef\u00E4hr?',a:["3","10","30","100"],_h:41},{q:'Was ist ein Nachteil der Globalisierung?',a:["Mehr Produktauswahl","Kultureller Austausch","Umweltbelastung durch lange Transportwege","Schnelleres Internet"],_h:99},{q:'Wie weit reist eine Jeans durchschnittlich?',a:["5.000 km","10.000 km","50.000 km","100.000 km"],_h:93}],boss:[{q:'Warum werden viele Produkte in Asien hergestellt, obwohl sie in Europa verkauft werden?',a:["Weil Asien n\u00E4her ist","Weil die Produktionskosten dort niedriger sind und trotz der Transportkosten der Gesamtpreis g\u00FCnstiger bleibt","Weil es in Europa keine Fabriken gibt","Weil die Qualit\u00E4t besser ist"],_h:126},{q:'Warum kann die Globalisierung sowohl Armut bek\u00E4mpfen als auch verst\u00E4rken?',a:["Weil es Zufall ist","Weil sie Arbeitspl\u00E4tze in Entwicklungsl\u00E4ndern schafft, aber gleichzeitig zu Ausbeutung und ungerechter Verteilung von Gewinnen f\u00FChren kann","Weil sie nur den Reichen hilft","Weil Armut nat\u00FCrlich ist"],_h:126},{q:'Warum ist das Internet ein wichtiger Faktor der Globalisierung?',a:["Weil man Spiele spielen kann","Weil es weltweite Kommunikation in Echtzeit erm\u00F6glicht, Handel erleichtert und Wissen f\u00FCr alle zug\u00E4nglich macht","Weil es schnell ist","Weil jeder ein Handy hat"],_h:126}]},{id:9,title:'Nachhaltigkeit',icon:'\u267B\uFE0F',duration:'30 Min.',description:'Erfahre was Klimawandel bedeutet und wie wir nachhaltig leben k\u00F6nnen.',lessons:[{title:'Der Klimawandel',content:\`<p>Der <strong>Klimawandel</strong> ist eine der gr\u00F6\u00DFten Herausforderungen unserer Zeit:</p>
<ul><li>\u{1F321}\uFE0F Die Erde hat sich seit 1900 um etwa <strong>1,1 \u00B0C</strong> erw\u00E4rmt</li><li>\u{1F4A8} Hauptursache: der <strong>Treibhauseffekt</strong> \u2014 CO\u2082 und andere Gase halten die W\u00E4rme in der Atmosph\u00E4re</li><li>\u{1F3ED} Durch Verbrennung fossiler Brennstoffe (Kohle, \u00D6l, Gas) steigt der CO\u2082-Gehalt</li><li>\u{1F9CA} Folgen: Gletscher schmelzen, der Meeresspiegel steigt, Extremwetter nehmen zu</li></ul>
<p><strong>Der nat\u00FCrliche Treibhauseffekt</strong> ist eigentlich gut \u2014 ohne ihn w\u00E4re die Erde -18 \u00B0C kalt! Aber der <strong>menschengemachte Treibhauseffekt</strong> verst\u00E4rkt ihn zu stark.</p>
<div class="info-box">\u26A0\uFE0F <strong>Wichtig:</strong> Wenn die Erw\u00E4rmung \u00FCber <em>1,5 \u00B0C</em> steigt, drohen unumkehrbare Folgen f\u00FCr \u00D6kosysteme weltweit!</div>\`},{title:'Nachhaltiges Handeln',content:\`<p><strong>Nachhaltigkeit</strong> bedeutet: So leben, dass auch zuk\u00FCnftige Generationen gut leben k\u00F6nnen.</p>
<p><strong>Erneuerbare Energien</strong> als Alternative zu fossilen Brennstoffen:</p>
<ul><li>\u2600\uFE0F <strong>Solarenergie</strong> \u2014 Strom aus Sonnenlicht</li><li>\u{1F4A8} <strong>Windkraft</strong> \u2014 Strom aus Windr\u00E4dern</li><li>\u{1F4A7} <strong>Wasserkraft</strong> \u2014 Strom aus flie\u00DFendem Wasser</li><li>\u{1F33F} <strong>Bioenergie</strong> \u2014 Energie aus Pflanzen und Abf\u00E4llen</li></ul>
<p><strong>Dein \u00F6kologischer Fu\u00DFabdruck</strong> \u2014 so kannst du ihn verkleinern:</p>
<ul><li>\u{1F6B2} Fahrrad statt Auto fahren</li><li>\u{1F957} Weniger Fleisch essen (Fleischproduktion verursacht viel CO\u2082)</li><li>\u267B\uFE0F M\u00FCll trennen und recyceln</li><li>\u{1F4A1} Strom sparen \u2014 Ger\u00E4te ausschalten, LED-Lampen nutzen</li><li>\u{1F455} Kleidung l\u00E4nger tragen, Second-Hand kaufen</li><li>\u{1F6D2} Regional und saisonal einkaufen</li></ul>
<div class="info-box">\u{1F31F} <strong>Jeder Beitrag z\u00E4hlt!</strong> Wenn alle Menschen kleine \u00C4nderungen vornehmen, macht das zusammen einen <em>riesigen Unterschied</em>!</div>\`}],quiz:[{q:'Was ist der Treibhauseffekt?',a:["Ein Gew\u00E4chshaus","Gase in der Atmosph\u00E4re halten W\u00E4rme zur\u00FCck","Ein Vulkanausbruch","Ein Sturm"],_h:75},{q:'Was ist KEINE erneuerbare Energie?',a:["Solarenergie","Windkraft","Kohle","Wasserkraft"],_h:125},{q:'Um wie viel Grad hat sich die Erde seit 1900 erw\u00E4rmt?',a:["0,1 \u00B0C","1,1 \u00B0C","5 \u00B0C","10 \u00B0C"],_h:42},{q:'Was versteht man unter Nachhaltigkeit?',a:["M\u00F6glichst viel kaufen","So leben, dass auch zuk\u00FCnftige Generationen gut leben k\u00F6nnen","Nur an heute denken","Immer das Neueste haben"],_h:96},{q:'Was verkleinert den \u00F6kologischen Fu\u00DFabdruck?',a:["Mehr Auto fahren","Fleisch essen","Fahrrad fahren und M\u00FCll trennen","Alles neu kaufen"],_h:93}],boss:[{q:'Warum ist der menschengemachte Treibhauseffekt problematisch, obwohl der nat\u00FCrliche Treibhauseffekt gut ist?',a:["Weil Treibhausgase giftig sind","Weil der Mensch durch die Verbrennung fossiler Brennstoffe den nat\u00FCrlichen Effekt so verst\u00E4rkt, dass die Erde sich zu schnell erw\u00E4rmt","Weil es keinen Unterschied gibt","Weil die Sonne st\u00E4rker scheint"],_h:126},{q:'Warum ist Fleischproduktion besonders klimasch\u00E4dlich?',a:["Weil Tiere laut sind","Weil Rinder Methan aussto\u00DFen, riesige Fl\u00E4chen f\u00FCr Futter ben\u00F6tigt werden und viel Wasser verbraucht wird","Weil Fleisch teuer ist","Weil K\u00FChe viel fressen"],_h:126},{q:'Warum reicht es nicht, nur auf erneuerbare Energien umzusteigen, um den Klimawandel zu stoppen?',a:["Weil erneuerbare Energien zu teuer sind","Weil auch Konsum, Ern\u00E4hrung, Transport und Landwirtschaft gro\u00DFe Mengen CO\u2082 verursachen und ebenfalls ver\u00E4ndert werden m\u00FCssen","Weil der Klimawandel nat\u00FCrlich ist","Weil es nicht genug Wind gibt"],_h:126}]}]`;

content = content.substring(0, startIdx) + newModules + content.substring(endIdx);
fs.writeFileSync(filePath, content, 'utf8');
console.log('Modules array replaced successfully');
console.log('New file size:', content.length);
